[project]
name = "led_animation_helper"
description = "small helper library for pre-selected and custom animations"
version = "0.0.0+auto.0"
authors = [
    {name = "Nicci Tynen", email = "ntynen@gmail.com"}
]
keywords = [
    "custom_animations"
]

[tools.setup]
packages = ["led_animation_helper"]